post_install() {
    getent passwd murmur > /dev/null || \
        useradd -d /var/lib/murmur -s /bin/bash murmur

    touch /var/log/murmur.log /var/run/murmur.pid

    chown -R murmur:murmur  /var/lib/murmur \
                            /var/log/murmur.log \
                            /var/run/murmur.pid
    echo
    echo '==> Set the SuperUser password with (as root):'
    echo '==>     murmur -supw PASSWORD'
}

post_upgrade() {
    post_install
}

pre_remove() {
    [ -f /var/run/daemons/murmur ] && /etc/rc.d/murmur stop > /dev/null
    killall -u murmur -5
    sleep 1
}

post_remove() {
    userdel murmur > /dev/null || \
        echo "error: could not delete user \"murmur\"" && \
        echo "deleted user \"murmur\" "
}
