--- old/Makefile	2009-10-27 13:01:42.000000000 -0500
+++ new/Makefile	2009-10-27 12:57:57.000000000 -0500
@@ -7,10 +7,10 @@
 #
 # **********************************************************************
 
-SUBDIRS			= cpp java cs py rb php
-CLEAN_SUBDIRS		= java cs py rb php cpp
-DEPEND_SUBDIRS		= cpp cs py rb php
-INSTALL_SUBDIRS		= cpp java cs py rb php
+SUBDIRS			= cpp java py
+CLEAN_SUBDIRS		= cpp java py
+DEPEND_SUBDIRS		= cpp java py
+INSTALL_SUBDIRS		= cpp java py
 
 all::
 	@for subdir in $(SUBDIRS); \
